### ISSUE TITLE
API calls get rate limited.

### ISSUE THREAD

**Issue by wwitzel3** [rdodev/oss-contribs#2]
Instead of failing, catch the 403 error and wait the timeout.

```Please enter your github username: wwitzel3
Retrieving all repositories by: wwitzel3

Preparing the spreadsheet...
Traceback (most recent call last):
  File "gh-repo-oss-contrib-xls.py", line 48, in <module>
    for r in reps:
  File "/home/wwitzel3/.local/share/virtualenvs/oss-contribs-zywGQleE/lib/python3.6/site-packages/github3/structs.py", line 76, in __iter__
    json = self._get_json(response)
  File "/home/wwitzel3/.local/share/virtualenvs/oss-contribs-zywGQleE/lib/python3.6/site-packages/github3/structs.py", line 111, in _get_json
    return self._json(response, 200)
  File "/home/wwitzel3/.local/share/virtualenvs/oss-contribs-zywGQleE/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.ForbiddenError: 403 API rate limit exceeded for 174.109.85.222. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)```

**Comment by wwitzel3** [comment]
I created a personal token at https://github.com/settings/tokens
And then I added a like `gh.login(token=TOKEN)` and was able to get around the rate limiting.

**Comment by rdodev** [comment]
Thanks. The web app which I posted in Slack and also the latest merge have the place to add personal token.
